defconfig: huashan: Align with android_kernel_sony_msm8960t
Author: Adrian DC <radian.dc@gmail.com>
Date:   Tue May 8 01:30:58 2018 +0200

    Revert "arm/configs: huashan: disable extra SCSI configs"

    This reverts commit 06485ccce500f905901189c422dc04fda00f2bca.
    Change-Id: Ic998bcee42c2bd1667d4c182887491ea66fb63c3

Author: Adrian DC <radian.dc@gmail.com>
Date:   Tue May 8 01:33:57 2018 +0200

    Revert "defconfig: huashan: Remove unused Huashan configuration"

    This reverts commit 020fed1f412394bedcc7e3a3ac604d4c7f70a611.
    Change-Id: Ibad4425633624fbfff25d1b00e8f100d6fb570cc

Author: Adrian DC <radian.dc@gmail.com>
Date:   Sun May 29 01:57:21 2016 +0200

    defconfig: huashan: Update configuration

     * Disable CONFIG_RELAY
     * Disable CONFIG_INPUT_MOUSEDEV
     * Enable CONFIG_PANIC_ON_DATA_CORRUPTION

    Change-Id: I2a51fab08ebee382b625b57123b79fd0bef7954f

Author: Adrian DC <radian.dc@gmail.com>
Date:   Mon Nov 14 01:09:58 2016 +0100

    defconfig: huashan: Enable CONFIG_INET_DIAG_DESTROY

    Change-Id: I0979b6957e9d10c9e627dd13335e2e7b48209b73

Author: Adrian DC <radian.dc@gmail.com>
Date:   Mon Nov 14 21:31:47 2016 +0100

    defconfig: huashan: Compress kernel with XZ

     * Without CONFIG_CC_OPTIMIZE_FOR_SIZE the kernel
        size is too large, the device is unable to power on

     * With default GZIP compression: ~7.7MB
     * With the XZ compression: ~5.3MB

    Change-Id: I17f697a6d38ff950936d9c8fd76d3dad760cffba

Author: Chris Fries <cfries@motorola.com>
Date:   Fri Dec 5 14:46:51 2014 -0600

    defconfig: huashan: Use -O2 not -Os

    Use -O2 instead of -Os for faster zram and disk performance.

    Penalty is about 1MB.

    Change-Id: Id2b3a2af67b9ad44dddce96b8624b34412d432ef
    Signed-off-by: Chris Fries <cfries@motorola.com>
    Reviewed-on: http://gerrit.mot.com/695621
    Tested-by: Jira Key <jirakey@motorola.com>
    Submit-Approved: Jira Key <jirakey@motorola.com>

Author: Adrian DC <radian.dc@gmail.com>
Date:   Thu Dec 8 19:14:32 2016 +0100

    defconfig: huashan: Move to a generic viskan_huashan_defconfig

     * cm_viskan_huashan_defconfig -> viskan_huashan_defconfig
     * cm_viskan_huashan_defconfig removed

    Change-Id: Ibfdeb961ba1d2ecd3c9e78424db4751dc4411bce
    Signed-off-by: Adrian DC <radian.dc@gmail.com>

Author: Adrian DC <radian.dc@gmail.com>
Date:   Thu Dec 8 19:21:33 2016 +0100

    defconfig: huashan: Enable RPFILTER (ipv4 and ipv6)

     * Due to system/netd Ia2e81786527b5718ed7f9dd195a39ea1eb7eb2b4,
        tethering now requires reverse path filter match support

    Change-Id: I9336d73596a98d67948417c0339b2c2d70ee4d6d

Author: Adrian DC <radian.dc@gmail.com>
Date:   Sat Apr 15 21:05:53 2017 +0200

    defconfig: huashan: Enable CONFIG_ANDROID_BINDER_IPC_32BIT

     * Use the old 32-bits binder API as our kernel runs on
        ARM 32bits, it should not compile  elements in 64bits,
        which would end in failures with following output:
        "undefined reference to `__get_user_bad'"

    Change-Id: Ib27c00f19847d19ad574e07d6f3c0a53cfeebb32

Author: Adrian DC <radian.dc@gmail.com>
Date:   Sat Apr 15 17:35:47 2017 +0200

    defconfig: huashan: enable CONFIG_QUOTA

     * Follows I7cb6b641f72085e69b90dca11d2ea68adcd02390

    Change-Id: Ifbbadf90d91ac8e40dfbf17f7e1ed30c774939fc

Author: Adrian DC <radian.dc@gmail.com>
Date:   Sat Apr 15 17:19:39 2017 +0200

    defconfig: huashan: enable SECCOMP config

     * Follows I2477b6a2cfdded5c0ebf6ffbb6150b0e5fe2ba12

    Change-Id: I4760377f3075af260435e505a21b202ba8f1d973

Author: Adrian DC <radian.dc@gmail.com>
Date:   Sat Apr 15 17:15:37 2017 +0200

    defconfig: huashan: remove CONFIG_IP[6]_NF_TARGET_REJECT_SKERR

     * Follows Ia1d63f3af21242e38418db208ec222e61e633615

    Change-Id: I8ee8ab3b61032fb49e146e5cd52b1e3cdd0aeb44

Author: John Dias <joaodias@google.com>
Date:   Mon Dec 5 17:15:18 2016 -0800

    defconfig: huashan: enable RCU_BOOST

    Enable RCU boost to avoid risk of priority-inversion
    and memory leaks when readers are preempted.

    Bug: 32633926
    Change-Id: I6de9b83c7f83646955e229a94078ae49c5962bc2
    Signed-off-by: John Dias <joaodias@google.com>

Author: Lorenzo Colitti <lorenzo@google.com>
Date:   Mon Jan 16 17:25:43 2017 +0900

    defconfig: huashan: enable CONFIG_CRYPTO_SHA512 and savedefconfig

    Bug: 34114242
    Change-Id: I7dbac97b1b76516e6ebb0491c57d9125ef9d25f3

Author: Tomoms <fondatommaso2@gmail.com>
Date:   Mon Sep 25 18:42:48 2017 +0200

    huashan: enable CONFIG_CONFIGFS_FS and CONFIG_SDCARD_FS

    Change-Id: Id0eff5dd60453079d2a2dc40731adfa3791d4e3b

Author: Patrick Tjin <pattjin@google.com>
Date:   Thu Sep 15 15:48:47 2016 -0700

    arm/configs: huashan: disable extra SCSI configs

    Bug: 30951599
    Change-Id: Ib5ff2322b4d08766d7aa7d2d0cc7ce2591420de0
    Signed-off-by: Patrick Tjin <pattjin@google.com>

Author: Artem Borisov <dedsa2002@gmail.com>
Date:   Tue Nov 7 19:09:49 2017 +0300

    huashan: defconfig: Use 64-bit binder API

    IPC_32BIT originally was intended to be used on 4.4 and older userspaces,
    because they didn't support new API and 64-bit pointers, but then it was
   forced on 32-bit platforms because ARM didn't have essential 64-bit get_user() calls.
    The main limitation of this option is that it is incompatible with new API,
    so kernel and userspace should have same binder version to work properly.
    Necessary calls were later introduced in commit "ARM: 8091/2: add get_user() support for 8 byte types"
    and now AOSP and mainline are going towards removing old 32-bit binder API support.
    64-bit binder is 100% compatible with 32-bit kernel and userspace,
    so there is no reason for us to keep using the old solution anymore.

    Change-Id: I91ce91a1a17ceb7110184657663e957bd8793d3f

Change-Id: I8b2d2ad062bd86e1b997c969ada6c61ca9202793
Signed-off-by: Adrian DC <radian.dc@gmail.com>